App\Context\OrderManagement\Domain\Order:
  type: entity
  table: om_order
  id:
    id:
      type: OrderId
  fields:
    status:
      type: string
  manyToMany:
    items:
      targetEntity: App\Context\OrderManagement\Domain\LineItem
      cascade: [ "persist", "remove" ]
      orphanRemoval: true
      joinTable:
        name: om_line_items_cross
        joinColumns:
          order_id:
            referencedColumnName: id
            onDelete: CASCADE
        inverseJoinColumns:
          order_item_id:
            referencedColumnName: id
            unique: true
            onDelete: CASCADE