doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci
        types:
            OrderId: App\Context\OrderManagement\Infrastructure\Type\OrderIdType
            LineItemId: App\Context\OrderManagement\Infrastructure\Type\LineItemIdType
            KitchenOrderId: App\Context\Kitchen\Infrastructure\Type\OrderIdType
            DishId: App\Context\Kitchen\Infrastructure\Type\DishIdType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.default
        auto_mapping: true
        mappings:
            context_shared:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Context/Shared/Infrastructure/Entity'
                prefix: 'App\Context\Shared\Domain'
            context_order_management:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Context/OrderManagement/Infrastructure/Entity'
                prefix: 'App\Context\OrderManagement\Domain'
            context_kitchen:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Context/Kitchen/Infrastructure/Entity'
                prefix: 'App\Context\Kitchen\Domain'
