parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:
    # Обработчики команд для шины
    App\Context\Shared\Application\Bus\Command\ICommandHandler:
      tags: [ 'messenger.message_handler' ]
    # Обработчики запросов для шины
    App\Context\Shared\Application\Bus\Query\IQueryHandler:
      tags: [ 'messenger.message_handler' ]
    # Обработчики событий
    App\Context\Shared\Application\IEventHandler:
      tags: [ 'kernel.event_listener' ]

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'

  App\Controller\:
    resource: '../src/Controller/'
    tags: [ 'controller.service_arguments' ]


  App\Context\Shared\Infrastructure\DomainEventsPlayer:
    tags:
      - { name: 'doctrine.event_subscriber' }