App\Context\Kitchen\Domain\Order:
  type: entity
  table: kitchen_order
  id:
    id:
      type: KitchenOrderId
  fields:
    cooked:
      type: boolean
  manyToMany:
    dishes:
      targetEntity: App\Context\Kitchen\Domain\Dish
      cascade: [ "persist", "remove" ]
      orphanRemoval: true
      joinTable:
        name: kitchen_order_dish_cross
        joinColumns:
          order_id:
            referencedColumnName: id
            onDelete: CASCADE
        inverseJoinColumns:
          dish_id:
            referencedColumnName: id
            unique: true
            onDelete: CASCADE